apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: global-traffic-policy
  namespace: istio-demo
spec:
  host: '*'
  trafficPolicy:
    outlierDetection:
      consecutiveGatewayErrors: 3
      interval: 100s
      baseEjectionTime: 3m
      maxEjectionPercent: 100